import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import SignIn from './login';
import RecoverPassword from './recover_password';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const Home: NextPage = () => {
  return (
    <div style={{ height: '100vh' }}>
      <Head>
        <title>GRAFIACidade</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main style={{ margin: '0', padding: '0' }}>
        <RecoverPassword />
        <ToastContainer />
      </main>
    </div>
  );
};

export default Home;
