import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import SignIn from './login/login';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GRAFIACidade</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main style={{ margin: '0', padding: '0' }}>
        <SignIn />
      </main>
    </div>
  );
};

export default Home;
